apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-product
  template:
    metadata:
      labels:
        app: mysql-product
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "2004"
            - name: MYSQL_DATABASE
              value: "k8s_product_db"